
* 虚拟存储器
    为了更加有效管理存储器并且少出错，现代系统提供了一种对主存的抽象概念，叫做 *虚拟存储器(VM)* . 虚拟存储器是硬件异常，硬件地址翻译，主存，磁盘文件和内核软件完善交互，它为每个进程提供了一个大的，一致的私有地址空间。通过一个很清晰机制，虚拟存储器提供了三个重要的能力:
- 它将主存看成是一个存储在磁盘上的地址空间的高速缓存，在主存中只保存活动区域,并根据需要在磁盘和主存之间来回传送数据，通过这种方式，它高效地使用主存.
- 它为每个进程提供一致的地址空间，从而简化存储器管理 
- 它保护了每个进程地址空间不被其他进程破坏
  
    程序员理解它有如下原因:
- 虚拟存储器是中心的
    虚拟存储器遍及计算机系统的所有层面，在硬件异常，汇编器，链接器，加载器，共享对象，文件和进程的设计中扮演着重要的角色。理解虚拟存储器将帮助你更好的理解系统通常是如何工作的。
- 虚拟存储器是强大的
    虚拟存储器给予应用程序强大能力，可以创建和销毁存储器片(chunk),将存储器片映射到磁盘文件的某个部分，以及与其他进程共享存储器。
- 虚拟存储器是危险的
    每次应用程序引用一个变量 ，间接引用一个指针，或者调用一个诸如malloc这样的动态分配程序时，它就会和虚拟存储器发生交互。如果虚拟存储器使用不当，应用将遇到复杂危险的与存储器有关的错误。

** 物理和虚拟寻址
   计算机系统的主存被组织成一个由M个连续的字节大小的单元组成的数组。每个字节都有一个唯 一的物理地址(Physical Address,PA).CPU最自然的方式就是使用物理地址，称为物理寻址.

   现代处理器使用的是一种称为虚拟寻址的寻址形式。

   使用虚拟寻址时，CPU通过生成一个虚拟地址(Virtual Address ,VA)来访问主存，这个虚拟地址在被送到存储器之前先转换成适当的物理地址。将一个虚拟地址转换为物理地址的任务叫做地址翻译(address translation),就像异常处理一样，地址翻译需要CPU硬件和操作系统之间的紧密合作。CPU芯片上叫做 *存储器管理单元(Memory Management Unit,MMU)* 的专用硬件，利用存放在主存中的查询表来动态翻译虚拟地址，该表的内容是由操作系统管理的。

** 地址空间
    地址空间(address space)是一个非负整数地址的有序集合:

    {0,1,2,...}

    如果地址空间中的整数是连续的，那么我们就说它是线性地址空间(linear address space).在一个带虚拟存储器的系统中，CPU从一个有N=2^n个地址的地址空间中生成虚拟地址，这个地址空间称为虚拟地址空间(virtual address space)

    一个系统还有一个物理地址空间(physical address space),它与系统中的物理存储器的M个字节对应.

    地址空间概念很重要，它清楚地区分了数据对象(字节)和它们的属性(地址).每个数据对象有多个独立的地址，其中每个地址都选自一个不同的地址空间。主存中的每个字节都有一个选自虚拟地址空间的虚拟地址和一个选自物理地址空间的物理地址.
