#+OPTIONS: ^:{} H:5 num:t
* 学会操纵工作,别让工作操控你

** 持续焦虑会把我们压垮

** 如果你使用outlook
   使用outlook管理时间(只作参考)

** 不用outlook的情况

* 时间都是整理出来的
  本书推荐的是"纸笔记录法",用纸和笔画出下面的列表，称为"工作流程表"

** 用纸笔开始时间整理
   取一页纸，顶部居中写上标题"当前工作列表".换行左对齐，写上标题"必办工作"(必须当天完成).

   然后，在纸张纸1/3处，同样左对齐，写上标题"待办工作"(本周或下周着手做,每日检查).第一页就是这些内容。


   接着取第二页纸，顶部居中写上标题"视限外的工作"(每周检查).

** 马上就行动起来
   马上制定表

** 如何使用"工作流程表"
   使用"工作流程表"有几个地方需要注意:
- 尽量把所有工作收集起来.
  收集工作甚至比执行工作更重要。不要一边收集一边工作，比如回复不痛不痒的邮件，发个快递，给中午提前订下餐，以为这些事件花不了多少时间，没想到回过神，一上午就没了。好的办法是把这些事件都变为工作任务，用一行小字描述这个任务，再填到表时，事无大小，都要集中到表中。一天忙碌结束时，只需要快速浏览一遍流程表,就能清楚知道哪些工作还没有完成,能不能收拾东西回家.

- 不要往"必办工作"栏里塞过多的工作.
  填入前先回答，如果下班时这项工作还没有完成，你愿不愿意加班把它处理完.
- "待办工作" 内容最好尽可能简短
  一旦这部分内容多于20项,就行筛选出不太重要的工作,移到"视限外的工作"云
- 如果一项"待办工作"有完成时限,最好注明
- "视限外的工作"最好每周过一遍清单.

** 列出的工作一定要靠谱
   凡是写在"必办工作"里的工作,都应该满足 "需要立即做"的要求.不要以为自己是神。否则每天压力会过大。所以你所列的工作一定要靠谱,不然会陷入"明天再做吧"的惰性循环

** 整理，整理，还是整理
   工作中我们常常会有这样的感觉： 不堪重负,手忙脚乱，起这样，不堪重负的感觉越强烈。因此有序安排工作，知道工作的轻重缓急，能够改变这种恶性循环的局面。

   首先 学会丢弃.尽量只保留工作必需品

   其次 每天使用的东西 尽量摆放在固定的位置 ，物品使用后要学会归位。

   再次 学会整理收纳发标和单据

* 为什么你的工作永远做不完
  要找到工作不堪重负的解决办法，先得问问自己:"为什么我觉得当前工作量，大到让自己不堪重负，甚至可能是恐惧呢?"

  许多人会说:"做的事太多了". 某些人确实在超负荷地工作，但有句话说得好，以大多数人的努力程序之低，根本轮不到拼天赋。很多人经常一到办公室，就会打开网页看看，再泡上一杯咖啡，逛逛购物网站。他们总想着还有一整天呢，待会儿再工作也不迟。因为没有“紧张感”，就无法把控工作，拖来拖去把正事都耽误了。

  我们来了解"把控"概念.说到把控某件事，往往基于这样的思维:这件事若做了就有好处，不做就有坏处。换句话说，这种管理手段就是奖励和惩罚。

** 工作需要适度紧迫感
   “高效能人士的7个习惯”对著名的四格象限做了全新的阐释，把“紧急”，“重要”放到坐标轴上，他认为，只有对目标很重要的事情，才需赶紧做，象限图中“紧急但不重要”的事尽量少做，这样一天中许多时间就解放出来。

   合理的紧迫感是一种管理工具，具有推动和激励作用。

** 为何总感觉被压得喘不过气
   时间太有限了，你却安排了太多的工作,还想一下子全部做好，当然容易崩溃。

   造成这种失控感还有一个原因是：即不清楚清单上究竟有哪些工作。一旦清单越来越长，工作积攒就越多。

** 被不重要的工作捆绑
   先做不重要的工作，可能是工作时间失控的主要原因。

   很多人习惯一收到email就马上浏览回复，这通常是忙非重要工作的表现,代价是把真正的事情放一边。

** 如何分清工作轻重缓急
   由于表里列太多工作，再要添加新内容时，很多重要的事情就直接跳过了，结果这些事情被搁置几周。

** 时间管理四象限法
   不堪重负感觉会导致恶性循环；不堪重负，因此更加手忙脚乱;越是手忙脚乱，不堪重负的感觉越强烈。从某种程序上讲，有序安排工作，知道工作的轻重，能够改变恶性循环局面

** 重要的少数与琐碎的多数

* 玩不转“当前工作”，如何拼职场
  接下来我们就要学习"时间管理金字塔"的把控层级部分。这套系统能让你把注意力集中在最关键的事项上，避免无意义的工作上耗费时间。

** 你的心智模式是什么
   "时间管理"不仅有缜密的逻辑性，同时还带有心理特征。因为它源于人们如何看待工作的分析：为何工作让人感到焦虑？为何我们担心其中一些项目，对另一些却得心应手？

   我拿一个心理学概念--心智模式    。来加以解释。沟通管理专家们多年来一直强调，解决员工间冲突，提高沟通效率，需要帮助他们了解彼此心智模式，搞清楚对方是如何看待工作的，了解对方在工作中的角色。随着对方的想法越来越清淅明朗，良好的沟通也就逐渐形成了。

   同时处理公司内工作压力，首先要清楚员工对待工作的心智模式。他们持有的心智模式产生了压力感，压力感又导致判断不清，判断不清反过来造成效率低下。

** 为何心智模式常常扭曲
   大家应该会看到一些"卡通地图"，地图会突出显示该地区与众不同的地方，一般是夸大重点地标。

** 心智模式 对工作效率的影响
   了解看待工作的心智模式，有助于解决工作中频繁出现的不堪重负的问题。我们对整个工作环境持有的心智模式有数十个甚至数百个，代表了我们对工作各层面的看法，例如职权，时间压力，薪酬，同事竞争，甚至办公设备，这些都体现我们与事实有出入的设想，一个心智模式对我们诠释工作的紧急性有极大的影响，它解释了为什么我们工作时常常效率低下.

** "当前视限" 心智模式
   我们总想把精力用于解决最紧急的事，然后是稍缓的过两天才需要解决的事，接着是紧急的再低些事.这期间有旁人打岔，但我们的焦点都集中在时限和紧急性上，这种心智模式便是我所谓的"当前视限"

** 确定你的"当前视限"

** 把工作当成流水线来管理

** "当前工作时间" 视限影响工作情绪

** 工作步伐很关键

** 看不到并非工作不存在

** 如何才能玩转当下

* 想做的太多，要分清工作的轻重缓急

** 你是否总在疲于奔命
   *如果你不管理工作，就会容易陷入"到处救火"的状态.* 你应该有过类似的情况，一整天忙个不停，眼看一天就要结束，内心焦躁不安，希望能像个超人一样把所有事情都做完。你只想着马上做，越快越好，速度是你解决问题的唯一对策。
   
   这种情况下，很容易做出错误的决定。上述工作者会进入一种状态，近似于 *注意力缺失症* .

   而专注于 *紧急事务区域* 的管理方法，能让各项工作的紧急程度清淅显示出来，看上去一目了然。

** 分清哪些工作是"必办"的
   我们选择三个紧急事务区域。

   最最重要的紧急事务区域，称之为 *必办工作区域*,它位于 *工作流程表* 第一页最顶端.

** 对待"待办工作"需要智慧
   *待办工作* 也就是完成必办工作后，当天还有富余时间精力可以机动灵活去做的工作。

** 冷静对待视限外的工作
   每周浏览一遍就行，心里有数.

** 管理工作两大原则
   首先 针对每项工作问自己：不完成是否需要加班到深夜？如果需要，就列入 *必办工作* 列表; 不需要,则不列入。

   第二项管理技巧: 把低优先级的工作转移到 *待办工作* 列表,并将工作数量减少到20项以下.

** 把潜伏在工作中的"鲨鱼"赶走
   *当前工作* 包含: *必办工作* 和 *待办工作* .

** 时刻谨记要事第一
   一旦你把紧急性从工作衡量标准中抽离出来，留下的就是我称之为 *固有的重要性* 的内容,它可以衡量一项工作与你的愿望，志向，核心价值观. 可以使用数字表示9表示最高.

* 如何不再为"小事"抓狂

** 当日事当日毕
   检查必须今天完成的紧急事务，然后将其填入 *必办工作* 列表,早上每天第一件事就是浏览一下 *待办工作* ,若发现其中有今天截止，便移入 *必办工作* 列表,保持必办工作列表只有今天必须今日完成的工作。
   
   *日事日清* 是很多公司提倡的工作法则，推脱和等待，是 *缺乏执行力的表现* .

** 提前完成工作,能激励人心
   使用 *工作流程表* ,能帮助我赶在合理时间前完成紧迫工作，对我而言很有吸引力。看着 *必办工作* 列表时，我可以自言自语地说:"做完这些，今天就可以去健身了",或者说:"这些完成后，我就能集中精力研究这些新创意了".无论哪种情况都相当激励人.

   提前完成 *必办工作* ，会带来一种抢在时间的前面的欣喜感。这种感觉相当美好，能改变你的整个工作态度，并能大大减轻工作压力。

** 不要高估自己的能力

** 分清"必须今日完成" 和 “对我十分重要”
   工作表短小精悍是原则，许多初学者往 *必办工作* 塞太多工作,原因在于他们分不清 *必须今日完成* 和 *对我十分重要*

** 学会把大工作分解成小工作

** 合理面对待办工作

** 千万别乱设工作期限

** 是的，工作总会越堆越多

** 待办工作不要超过 20项
*** 高效能4D系统::Do(执行), Deleted(删除),Delegate(授权),Defer(延迟)


   
   
